applicationName: Legend SDLC

server:
  adminContextPath: /sdlc/admin
  applicationConnectors:
    - type: http
      port: 7070
      maxRequestHeaderSize: 128KiB
  adminConnectors:
    - type: http
      port: 7071
  gzip:
    includedMethods:
      - GET
      - POST
  requestLog:
    type: classic
    level: OFF
    appenders:
      - type: console
        logFormat: "OFF"
  rootPath: /sdlc/api

projectStructure:
  projectCreation:
    groupIdPattern: ^org\.finos\.legend\..+
  extensionProvider:
    org.finos.legend.sdlc.server.gitlab.finos.FinosGitlabProjectStructureExtensionProvider: {}

filterPriorities:
  GitLab: 1
  org.pac4j.j2e.filter.CallbackFilter: 2
  org.pac4j.j2e.filter.SecurityFilter: 3
  CORS: 4

pac4j:
  callbackPrefix: /sdlc/api/pac4j/login
  mongoUri: mongodb://admin:password@legend-demo-mongodb:27017
  mongoDb: legend
  clients:
    - org.finos.legend.server.pac4j.gitlab.GitlabClient:
        name: gitlab
        clientId: __GITLAB_CLIENT_ID__
        secret: __GITLAB_SECRET__
        discoveryUri: https://gitlab.com/.well-known/openid-configuration
        scope: openid profile api
  mongoSession:
      enabled: true
      collection: userSessions
  bypassPaths:
    - /sdlc/api/info

features:
  canCreateProject: false
  canCreateVersion: false

gitLab:
  newProjectVisibility: public
  projectTag: pure
  projectIdPrefix: UAT
  server:
    scheme: https
    host: gitlab.com
  app:
    id: __GITLAB_CLIENT_ID__
    secret: __GITLAB_SECRET__
    redirectURI: http://localhost:7070/api/auth/callback


logging:
  # Change this to affect library class logging
  level: INFO
  appenders:
    - type: console
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%thread] %c - %m%n"

swagger:
  resourcePackage: org.finos.legend.sdlc.server.resources
  title: Legend LEGEND_SDLC
  version: local-snapshot
  schemes: []
